//
// Created by Jj on 23/07/2023.
//

#ifndef CHECKERS_UI_CONSTANTS_H
#define CHECKERS_UI_CONSTANTS_H


// COLORS
#define COLOR_ROSE al_map_rgb(0xFF, 0xD2, 0xD7)
#define COLOR_GRAY al_map_rgb(0x92, 0x88, 0xF8)
#define COLOR_PURPLE al_map_rgb(0x80, 0x62, 0xD6)
#define COLOR_DARK_GRAY al_map_rgb(0x32, 0x26, 0x53)
#define COLOR_WHITE al_map_rgb(255, 255, 255)
#define COLOR_BLACK al_map_rgb(0, 0, 0)


#define WHITE_SQUARE_COLOR COLOR_ROSE
#define BLACK_SQUARE_COLOR COLOR_GRAY

#define WHITE_PAWN_COLOR COLOR_WHITE
#define BLACK_PAWN_COLOR COLOR_BLACK

#define WHITE_QUEEN_COLOR COLOR_BLACK
#define BLACK_QUEEN_COLOR COLOR_ROSE

#define BACKGROUND_COLOR COLOR_DARK_GRAY
#define BOARD_BORDER_COLOR COLOR_WHITE

#define BUTTON_COLOR COLOR_PURPLE
#define BUTTON_BORDER_COLOR COLOR_DARK_GRAY

#define COORDINATE_FONT_COLOR COLOR_WHITE

#define SELECTED_SQUARE_COLOR al_map_rgb(255, 255, 0)
#define POSSIBLE_MOVE_COLOR al_map_rgb(255, 0, 0)

//SIZE CONSTANTS
#define SQUARE_SIZE 80

#define LEFT_PANEL_WIDTH 80
#define RIGHT_PANEL_WIDTH 480
#define TOP_PANEL_HEIGHT 80
#define BOTTOM_PANEL_HEIGHT 80

#define MENU_BUTTON_WIDTH 320
#define MENU_BUTTON_HEIGHT 80


#define PAWN_RADIUS ((float)SQUARE_SIZE / 2 - 15)
#define QUEEN_RADIUS ((float)SQUARE_SIZE / 2 - 11)



#endif //CHECKERS_UI_CONSTANTS_H
